# Generated by Django 5.0.3 on 2024-03-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userObj', models.JSONField(blank=True, default={'users': []})),
            ],
            options={
                'db_table': 'uList',
            },
        ),
    ]
