# Generated by Django 5.0.3 on 2024-03-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_userdata_sessionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='connectionRequest',
            new_name='connectionRecieved',
        ),
        migrations.AddField(
            model_name='userdata',
            name='connectionSent',
            field=models.JSONField(blank=True, default={'requests': []}),
        ),
    ]
