# Generated by Django 5.0.3 on 2024-03-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='sessionId',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
