# Generated by Django 5.0.3 on 2024-03-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_rename_connectionrequest_userdata_connectionrecieved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='assignedTask',
            field=models.JSONField(blank=True, default={'tasks': []}),
        ),
        migrations.AddField(
            model_name='userdata',
            name='selfTask',
            field=models.JSONField(blank=True, default={'tasks': []}),
        ),
    ]
