# Generated by Django 5.0.3 on 2024-03-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_userdata_sessionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='activeConnections',
            field=models.JSONField(blank=True, default={'connections': []}),
        ),
        migrations.AddField(
            model_name='userdata',
            name='connectionRequest',
            field=models.JSONField(blank=True, default={'requests': []}),
        ),
    ]
