# Generated by Django 5.0.3 on 2024-03-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminUser',
        ),
    ]
