# Generated by Django 5.0.3 on 2024-03-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='feedback',
            field=models.JSONField(blank=True, default={'feedbacks': []}),
        ),
    ]
