# Generated by Django 5.0.3 on 2024-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_userdata_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='updationQueue',
            field=models.JSONField(blank=True, default={'queue': []}),
        ),
    ]
